version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kingRoadDB
      MYSQL_USER: kingroad
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s

  king-road-api:
    build:
      context: ./king-road-api
      args:
        PHP_VERSION: 8.2
    platform: linux/amd64
    container_name: king-road-api
    restart: unless-stopped
    volumes:
      - ./king-road-api:/var/www/html
      - ./king-road-api/routes:/var/www/html/routes
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=kingRoadDB
      - DB_USERNAME=kingroad
      - DB_PASSWORD=1234
    command: sh -c "docker-php-ext-install zip && composer install --ignore-platform-reqs && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # king-road-website:
  #   build:
  #     context: ./king-road-website
  #     dockerfile: Dockerfile
  #   container_name: king-road-website
  #   volumes:
  #     - ./king-road-website:/app
  #     - /app/node_modules # prevents overwriting node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm run dev

  king-road-admin:
    build:
      context: ./king-road-admin
      dockerfile: Dockerfile
    container_name: king-road-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

# ⬇️ Move this block to the bottom (outside services)
volumes:
  mysql_data:
