"use client";

import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations: any = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.orders": "Orders",
    "nav.analytics": "Analytics",
    "nav.customers": "Customers",
    "nav.messages": "Messages",
    "nav.inventory": "Inventory",
    "nav.finances": "Finances",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.language": "العربية",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Here's what's happening with your store today",

    // Common
    "common.search": "Search...",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.create": "Create",
    "common.manage": "Manage",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.export": "Export",
    "common.import": "Import",
    "common.refresh": "Refresh",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.reset": "Reset",
    "common.clear": "Clear",
    "common.select": "Select",
    "common.upload": "Upload",
    "common.download": "Download",
    "common.print": "Print",
    "common.share": "Share",
    "common.copy": "Copy",
    "common.paste": "Paste",
    "common.cut": "Cut",
    "common.undo": "Undo",
    "common.redo": "Redo",
    "common.help": "Help",
    "common.about": "About",
    "common.contact": "Contact",
    "common.privacy": "Privacy",
    "common.terms": "Terms",
    "common.logout": "Logout",
    "common.login": "Login",
    "common.register": "Register",
    "common.profile": "Profile",
    "common.account": "Account",
    "common.dashboard": "Dashboard",
    "common.overview": "Overview",
    "common.details": "Details",
    "common.summary": "Summary",
    "common.total": "Total",
    "common.subtotal": "Subtotal",
    "common.tax": "Tax",
    "common.shipping": "Shipping",
    "common.discount": "Discount",
    "common.coupon": "Coupon",
    "common.price": "Price",
    "common.quantity": "Quantity",
    "common.amount": "Amount",
    "common.date": "Date",
    "common.time": "Time",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.yes": "Yes",
    "common.no": "No",
    "common.true": "True",
    "common.false": "False",
    "common.on": "On",
    "common.off": "Off",
    "common.public": "Public",
    "common.private": "Private",
    "common.draft": "Draft",
    "common.published": "Published",
    "common.pending": "Pending",
    "common.approved": "Approved",
    "common.rejected": "Rejected",
    "common.completed": "Completed",
    "common.cancelled": "Cancelled",
    "common.refunded": "Refunded",
    "common.shipped": "Shipped",
    "common.delivered": "Delivered",
    "common.processing": "Processing",
    "common.confirmed": "Confirmed",
    "common.unconfirmed": "Unconfirmed",
    "common.verified": "Verified",
    "common.unverified": "Unverified",
    "common.available": "Available",
    "common.unavailable": "Unavailable",
    "common.in_stock": "In Stock",
    "common.out_of_stock": "Out of Stock",
    "common.low_stock": "Low Stock",
    "common.unlimited": "Unlimited",
    "common.limited": "Limited",
    "common.featured": "Featured",
    "common.popular": "Popular",
    "common.trending": "Trending",
    "common.new": "New",
    "common.sale": "Sale",
    "common.bestseller": "Bestseller",
    "common.recommended": "Recommended",
    "common.related": "Related",
    "common.similar": "Similar",
    "common.other": "Other",
    "common.more": "More",
    "common.less": "Less",
    "common.all": "All",
    "common.none": "None",
    "common.any": "Any",
    "common.every": "Every",
    "common.each": "Each",
    "common.some": "Some",
    "common.many": "Many",
    "common.few": "Few",
    "common.several": "Several",
    "common.multiple": "Multiple",
    "common.single": "Single",
    "common.double": "Double",
    "common.triple": "Triple",
    "common.first": "First",
    "common.second": "Second",
    "common.third": "Third",
    "common.last": "Last",
    "common.latest": "Latest",
    "common.oldest": "Oldest",
    "common.newest": "Newest",
    "common.recent": "Recent",
    "common.current": "Current",
    "common.upcoming": "Upcoming",
    "common.past": "Past",
    "common.future": "Future",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.tomorrow": "Tomorrow",
    "common.week": "Week",
    "common.month": "Month",
    "common.year": "Year",
    "common.daily": "Daily",
    "common.weekly": "Weekly",
    "common.monthly": "Monthly",
    "common.yearly": "Yearly",
    "common.hourly": "Hourly",
    "common.minute": "Minute",

    "common.millisecond": "Millisecond",
    "common.timezone": "Timezone",
    "common.currency": "AED",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.products": "المنتجات",
    "nav.orders": "الطلبات",
    "nav.analytics": "التحليلات",
    "nav.customers": "العملاء",
    "nav.messages": "الرسائل",
    "nav.inventory": "المخزون",
    "nav.finances": "المالية",
    "nav.reports": "التقارير",
    "nav.settings": "الإعدادات",
    "nav.language": "English",

    // Dashboard
    "dashboard.welcome": "مرحباً بعودتك",
    "dashboard.overview": "إليك ما يحدث في متجرك اليوم",

    // Common
    "common.search": "بحث...",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ ما",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.add": "إضافة",
    "common.remove": "إزالة",
    "common.update": "تحديث",
    "common.create": "إنشاء",
    "common.manage": "إدارة",
    "common.filter": "تصفية",
    "common.sort": "ترتيب",
    "common.export": "تصدير",
    "common.import": "استيراد",
    "common.refresh": "تحديث",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.reset": "إعادة تعيين",
    "common.clear": "مسح",
    "common.select": "اختيار",
    "common.upload": "رفع",
    "common.download": "تحميل",
    "common.print": "طباعة",
    "common.share": "مشاركة",
    "common.copy": "نسخ",
    "common.paste": "لصق",
    "common.cut": "قص",
    "common.undo": "تراجع",
    "common.redo": "إعادة",
    "common.help": "مساعدة",
    "common.about": "حول",
    "common.contact": "اتصال",
    "common.privacy": "الخصوصية",
    "common.terms": "الشروط",
    "common.logout": "تسجيل الخروج",
    "common.login": "تسجيل الدخول",
    "common.register": "التسجيل",
    "common.profile": "الملف الشخصي",
    "common.account": "الحساب",
    "common.dashboard": "لوحة التحكم",
    "common.overview": "نظرة عامة",
    "common.details": "التفاصيل",
    "common.summary": "الملخص",
    "common.total": "المجموع",
    "common.subtotal": "المجموع الفرعي",
    "common.tax": "الضريبة",
    "common.shipping": "الشحن",
    "common.discount": "الخصم",
    "common.coupon": "الكوبون",
    "common.price": "السعر",
    "common.quantity": "الكمية",
    "common.amount": "المبلغ",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.status": "الحالة",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.enabled": "مفعل",
    "common.disabled": "معطل",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.true": "صحيح",
    "common.false": "خطأ",
    "common.on": "تشغيل",
    "common.off": "إيقاف",
    "common.public": "عام",
    "common.private": "خاص",
    "common.draft": "مسودة",
    "common.published": "منشور",
    "common.pending": "معلق",
    "common.approved": "موافق عليه",
    "common.rejected": "مرفوض",
    "common.completed": "مكتمل",
    "common.cancelled": "ملغي",
    "common.refunded": "مسترد",
    "common.shipped": "مشحون",
    "common.delivered": "مسلم",
    "common.processing": "قيد المعالجة",
    "common.confirmed": "مؤكد",
    "common.unconfirmed": "غير مؤكد",
    "common.verified": "موثق",
    "common.unverified": "غير موثق",
    "common.available": "متاح",
    "common.unavailable": "غير متاح",
    "common.in_stock": "متوفر",
    "common.out_of_stock": "نفد المخزون",
    "common.low_stock": "مخزون منخفض",
    "common.unlimited": "غير محدود",
    "common.limited": "محدود",
    "common.featured": "مميز",
    "common.popular": "شائع",
    "common.trending": "رائج",
    "common.new": "جديد",
    "common.sale": "تخفيض",
    "common.bestseller": "الأكثر مبيعاً",
    "common.recommended": "موصى به",
    "common.related": "ذات صلة",
    "common.similar": "مشابه",
    "common.other": "أخرى",
    "common.more": "المزيد",
    "common.less": "أقل",
    "common.all": "الكل",
    "common.none": "لا شيء",
    "common.any": "أي",
    "common.every": "كل",
    "common.each": "كل واحد",
    "common.some": "بعض",
    "common.many": "كثير",
    "common.few": "قليل",
    "common.several": "عدة",
    "common.multiple": "متعدد",
    "common.single": "واحد",
    "common.double": "مضاعف",
    "common.triple": "ثلاثي",
    "common.first": "الأول",
    "common.second": "الثاني",
    "common.third": "الثالث",
    "common.last": "الأخير",
    "common.latest": "الأحدث",
    "common.oldest": "الأقدم",
    "common.newest": "الأجدد",
    "common.recent": "حديث",
    "common.current": "الحالي",
    "common.upcoming": "القادم",
    "common.past": "الماضي",
    "common.future": "المستقبل",
    "common.today": "اليوم",
    "common.yesterday": "أمس",
    "common.tomorrow": "غداً",
    "common.week": "أسبوع",
    "common.month": "شهر",
    "common.year": "سنة",
    "common.daily": "يومي",
    "common.weekly": "أسبوعي",
    "common.monthly": "شهري",
    "common.yearly": "سنوي",
    "common.hourly": "كل ساعة",
    "common.minute": "دقيقة",
    "common.millisecond": "ميلي ثانية",
    "common.timezone": "المنطقة الزمنية",
    "common.currency": "درهم",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("vendor-language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("vendor-language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: any) => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
        isRTL,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
